@startuml activity_purchase
title 購入から視聴まで

|BackEnd|
start
:レシートを作成する;
:レシートをブロックチェーン上に記録する;

fork
    while (ブロックチェーン上に書き込まれた?)
        :自分の残高を見に行く;
        note left
            残高が変化していれば、
            書き込まれている。
        endnote
    endwhile
|FrontEnd|
fork again
    :処理中表示;
    note left
        １分くらいかかる
    endnote
end fork

:動画をロードする;
:動画を表示する;

|BackEnd|
end

@enduml